# These are supported funding model platforms

github: # [termalikjis, user2]

BTC: # [btc:bc1q7d0tm49g07mxgwut38zfte3v0vd89wr4079ty3] // from 500 USD. Thanks you!
ETC: # [etc:0x02316c0c88fC67aCDF07b4F34b0D32b28BAdc5B8] // from 200 USD. Thanks you!
