# These are supported funding model platforms

github: # @termalikjis, @user2

BTC: # bc1q 7d0t m49g 07mx gwut3 8zft e3v0 vd89 wr40 79ty3 /// from 500 USD. Thanks you!
ETC: # 0x02 316c 0c88 fC67 aCDF0 7b4F 34b0 D32b 28BA dc5B8 /// from 200 USD. Thanks you!
